import numpy

import openGB.polynomials as polys


class Ideal:
    '''
    Ideals generated by set of polynomials    
    '''
    def __init__(self, polynomials, order):
        '''
        Parameters
        Polynomial[] polynomials -- a sequence of polynomials
        MonomialOrder order -- a monomial order applied to the polynomials
        '''
        self.polynomials = polynomials
        self.order = order
        self.isGB = False

    def sort(self):
        '''
        Sorts all monomials in polynomials
        '''
        pass

    #a fancy-looking string representation
    def __str__(self):
        pass

    def checkGB(self):
        '''
        Checks if the set of polynomials forms a GB
        '''
        pass

    def computeGB(self):
        '''
        Computes a Groebner Basis using Buchberger algorithm
        '''
        pass
